language:
  - node_js
  - java
node_js:
  - "0.8"
jdk: oraclejdk7

before_install:
  - chmod +x $PWD/.travis_install_skilap.sh
  - $PWD/.travis_install_skilap.sh
 
script: 
  - cd skilap
  - ant debug install -Dsdk.dir=$ANDROID_HOME
  - cd ..
  - ls
  - cd skilapTest
  - ant release test -Dsdk.dir=$ANDROID_HOME
